### ISSUE TITLE
Error in gather_candidates

### ISSUE THREAD

**Issue by rafaqz** [msprev/unite-bibtex#1]
Here's the output I'm getting in vim after attempting :Unite bibtex

[unite.vim] function <SNR>51_call_unite[33]..unite#start[1]..unite#start#standard[50]..unite#candidates#_recache[74]..<SNR>134_recache_candidates_loop
[41]..<SNR>134_get_source_candidates[40]..124, line 25
[unite.vim] Vim(python):Traceback (most recent call last):
[unite.vim] Error occurred in gather_candidates!
[unite.vim] Source name is bibtex

Any ideas?

**Comment by msprev** [comment]
vim python doesn't give the most informative error messages! This is basically saying that an exception has been thrown somewhere but gives no clue where. The first thing to check is whether `bibtexparser` has been installed for python2. Try typing on the command line:

```
python2
import bibtexparser
```

and see if that generates any errors.

**Comment by msprev** [comment]
Scratch that! You can test by issuing this command in vim:

```
:pydo import bibtexparser
```

Does this generate any error message? If so, then `bibtexparser` hasn't been installed properly. 

If not, try `Unite bibtex` with only a tiny and clean bibtex file. If it works with this minimal file, then your original bibtex file is probably not 100% valid bibtex (v common) and it is generating a parsing error. You should try to find the errors (see the tool suggested in troubleshooting in readme, or use a tool like JabRef).

**Comment by rafaqz** [comment]
I'm not really sure what a minimal file is, but I've got one article exported from zotero, checked with pybtex-convert and still no bananas. It would be great to have more informative error messages!

**Comment by msprev** [comment]
Hmm. Could you try running it with a bib file with just this entry?

```
@book{Test01,
    Address = {Somewhere},
    Author = {Author, A.},
    Publisher = {Publisher},
    Title = {Title},
    Year = {2010},
    }
```

**Comment by rafaqz** [comment]
Yep that works. I've got it working now, I think the problem was that I was
using straight bibtex export from zotero instead of better bibtex.

**Comment by msprev** [comment]
Wonderful! It must have been `bibtexparser` that was throwing the exception. bibtex is a pretty nasty format to parse: it's not easy to validate and lots of folks don't have bibtex files that aren't 100% valid despite being readable by some pieces of software. Great to hear you have it working.
