### ISSUE TITLE
Compatibility with biblatex

### ISSUE THREAD

**Issue by twsh** [msprev/unite-bibtex#2]
Thanks for this!

I use slightly different field names, following what's in the biblatex manual:

journal -> journaltitle
year -> date
address -> location

I've forked your code and edited apalike.py to handle both: https://github.com/twsh/unite-bibtex

Would you be amenable to a pull request?

**Comment by msprev** [comment]
Yes, please! Thank you for doing this. Please send a PR and I'll merge it.

**Comment by twsh** [comment]
I will.

**Comment by twsh** [comment]
I'm afraid it's not working for me: I get 'no year', '==no title=='.

I don't think the logic of `get` is right: The function will be passed 'year', 'journal', and 'address' so the conditional will always be true, right?

I was thinking that you could reverse the dictionary and do it this way:

```
def get(e, key, default):
    """
    return e.get(key, default)
    if standard bibtex version of key not found, use biblatex version
    """
    BIBLATEX = {'year': 'date',
                'journal': 'journaltitle',
                'address': 'location'}
    if key not in e and key in BIBLATEX and BIBLATEX[key] in e:
        return e.get(BIBLATEX[key], default)
    else:
        return e.get(key, default)
```

**Comment by msprev** [comment]
oops, fixed now I think! Thanks. Please let me know if it doesn't work.

**Comment by twsh** [comment]
That's working for me now with my biblatex file. Thanks!

**Comment by msprev** [comment]
Brilliant! Thank you for letting me know. Sorry for the mangled logic earlier.
