### ISSUE TITLE
bibtexparser and 'non standard types'

### ISSUE THREAD

**Issue by twsh** [msprev/unite-bibtex#5]
bibtexparser raises an error when it encounters a 'non standard type' in a .bib file. It counts types like 'collection' as nonstandard. unite-bibtex now displays the warnings when it builds its cache. One way to stop this would be to use a `ignore_nonstandard_types=False` option with the parser.

**Comment by msprev** [comment]
Thanks for finding this option! I've added it now and pushed the change.

**Comment by twsh** [comment]
Great! I get no errors now.
