### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by twsh** [msprev/unite-bibtex#7]
My fork https://github.com/twsh/unite-bibtex works with Python 3, but, at present, only Python 3. I haven't thought yet about how to have one thing that works whichever Python Vim has.

**Comment by msprev** [comment]
It would be desirable to have a single version of the plugin that works with python2 or python3 in vim. This should be do-able.

I quickly downloaded your fork, but it still kicks out an error when I go to `core` on the command line, go the Python repl and try to `import gather`. So I don't think that the conversion to Python3 is complete yet. (One of my pet hates with Python is the rules of the packaging system).  I'll require me to find a few hours to debug what is going wrong here. I can't do this right now, but it's on my todo list.

**Comment by twsh** [comment]
I get an error when I do that too:

```
>>> import gather
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/t/Code/unite-bibtex/pythonx/core/gather.py", line 1, in <module>
    from . import bibtex
SystemError: Parent module '' not loaded, cannot perform relative import
```

But the plugin does work. I installed my fork through Vundle and I've been using it. One issue I think is that Vim's Python uses a different path. One example being that it allows `import core.gather`.

What seems to work is to have all the imports as explicit relative paths except for the importing of gather.py in unitebibtex.py.

**Comment by msprev** [comment]
It's good that it is working for you, but I'd like to get it 100% correct. I'm currently a bit swamped but I'll get to it!

**Comment by twsh** [comment]
I've just pushed a commit where I use the future module to make my code compatible with Python 2.

**Comment by msprev** [comment]
I'm closing this issue because because unite-bibtex has been retired. A new tool, [fzf-bibtex](https://github.com/msprev/fzf-bibtex), replaces it. This avoids any dependence on vim's Python and it is blazingly fast.
